import {parseRecords,defaultStep,newWorkflow} from './live-data.mjs';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n?'$'+(n/100).toFixed(2):'Free',pretty=v=>JSON.stringify(v,null,2);
let state=null,view=location.hash.slice(1)||'campaigns',busy=false,detailId=null,editing=null,toastTimer;
const names={campaigns:'Campaigns',marketplace:'Marketplace',creators:'Creator studio',connectors:'API connections',activity:'Activity',connections:'System status',platforms:'API connections',assistant:'AI assistant'};
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),5000);}
async function request(route,body){const headers={};if(body!==undefined){const session=await fetch('/api/session',{cache:'no-store'}).then(r=>r.json());headers['x-hyperaccts-token']=session.csrf;headers['content-type']='application/json';}
 const r=await fetch('/api/runtime/'+route,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.message||'Request failed.'),{status:r.status});return data;}
async function refresh(){if(busy)return;busy=true;try{const next=await request('state'),changed=JSON.stringify(next)!==JSON.stringify(state);state=next;$('#service-status').textContent='Connected · changes saved';$('#nav-count').textContent=state.campaigns.length;if(changed&&!$('dialog[open]')&&!$('#app form'))render();if(changed&&detailId&&$('#details').open)showDetails(detailId,false);}catch(e){$('#service-status').textContent='Service unavailable';if(e.status===401)login();else toast(e.message);}finally{busy=false;}}
function heading(title,description,action=''){return `<div class="page-heading"><div><div class="eyebrow">YOUR WORKSPACE</div><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${action}</div>`;}
function empty(title,text,action=''){return `<div class="panel empty"><h3>${esc(title)}</h3><p>${esc(text)}</p>${action}</div>`;}
const button=(text,action,id='',cls='')=>`<button class="${cls}" data-action="${action}" data-id="${esc(id)}">${esc(text)}</button>`;
const field=(label,name,value='',type='text',attrs='')=>`<label>${esc(label)}<input name="${esc(name)}" type="${type}" value="${esc(value)}" ${attrs}></label>`;
const area=(label,name,value,attrs='')=>`<label class="full">${esc(label)}<textarea name="${esc(name)}" ${attrs}>${esc(value)}</textarea></label>`;
function modal(id,title,content){const d=$('#'+id);d.innerHTML=`<div class="modal-head"><h2 id="${id==='details'?'details-title':'wizard-title'}">${esc(title)}</h2><button class="close-btn" data-action="close" aria-label="Close">×</button></div><div class="modal-body">${content}</div>`;if(!d.open)d.showModal();return d;}
function render(){if(!state)return;document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));$('#breadcrumb').textContent='Workspace / '+(names[view]||'Campaigns');
 const panels={campaigns:campaigns,marketplace:marketplace,creators:creators,connectors:connections,platforms:connections,activity:activity,connections:status,assistant:assistant};$('#app').innerHTML=(panels[view]||campaigns)();}
function campaigns(){const c=state.campaigns,total=c.reduce((n,x)=>n+x.records.length,0);return heading('Campaigns','Run installed workflows against your records and connected APIs.',button('New campaign','new-campaign','','primary'))+`<div class="stats">${[['Campaigns',c.length],['Running',c.filter(x=>x.status==='running').length],['Records',total],['Needs review',c.reduce((n,x)=>n+x.records.filter(r=>r.status==='review').length,0)]].map(([label,n])=>`<div class="stat"><span>${label}</span><h2>${n}</h2></div>`).join('')}</div>`+(c.length?`<div class="panel"><div class="table-scroll"><table><thead><tr><th>Campaign</th><th>Workflow</th><th>Status</th><th>Completed</th><th></th></tr></thead><tbody>${c.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x.workflow.title)}<small> v${esc(x.workflow.version)}</small></td><td>${esc(x.status)}</td><td>${x.records.filter(r=>r.status==='completed').length} / ${x.records.length}</td><td>${button('Open','details',x.id)}</td></tr>`).join('')}</tbody></table></div></div>`:empty('Create your first campaign','Install a workflow from the marketplace, import your records, and choose when it runs.',button('Browse workflows','nav','marketplace')));}
function marketplace(){return heading('Workflow marketplace','Install a published version. Campaigns keep the exact version you choose.')+`<div class="solution-grid">${state.catalog.map(p=>`<article class="solution-card"><div><h3>${esc(p.workflow.title)}</h3><div class="creator-by">${esc(p.creator)} · v${esc(p.workflow.version)}</div></div><p>${esc(p.workflow.description)}</p><div class="permission-list">${[...new Set(p.workflow.steps.map(s=>s.type))].map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="solution-meta"><b>${money(p.workflow.priceCents)}</b>${p.installed?button('Create campaign','new-campaign',p.id,'primary'):button(p.workflow.priceCents?'Buy workflow':'Install','install',p.id)}</div>${p.workflow.priceCents&&!state.paymentsReady?'<small>Paid checkout needs marketplace payment setup.</small>':''}</article>`).join('')}</div>`;}
function creators(){return heading('Creator studio','Build executable steps, publish a reviewed version, and share it.',button('New workflow','new-workflow','','primary'))+`<div class="notice">Published versions are immutable. Edit a draft and increase its version to release an update.</div><div class="solution-grid">${state.drafts.map(d=>`<article class="solution-card"><h3>${esc(d.workflow.title)}</h3><p>v${esc(d.workflow.version)} · ${esc(d.status)} · ${d.workflow.steps.length} steps</p>${d.reviewNote?`<p>${esc(d.reviewNote)}</p>`:''}<div class="detail-actions">${button('Edit','edit-workflow',d.id)}${d.status==='draft'||d.status==='rejected'?button('Submit for review','submit-workflow',d.id):''}</div></article>`).join('')||'<p>No drafts yet.</p>'}</div>`+(state.user.admin?`<h2 class="creator-section">Publishing review</h2>${state.reviews.map(d=>`<article class="panel connection-card"><h3>${esc(d.workflow.title)} · ${esc(d.creator)}</h3><pre>${esc(pretty(d.workflow))}</pre><div class="detail-actions">${button('Approve publication','publish',d.id)}${button('Reject','reject-publication',d.id)}</div></article>`).join('')||'<p>No submissions waiting for review.</p>'}`:'')+`<div class="notice">Paid workflows require a connected Stripe payout account. ${button('Set up payouts','onboard')}</div>`;}
function connections(){return heading('API connections','Connect an API you are authorized to use. Credentials are encrypted on the service.',button('Add connection','new-connection','','primary'))+`<div class="solution-grid">${state.connections.map(c=>`<article class="solution-card"><h3>${esc(c.name)}</h3><p>${esc(c.origin)}</p><small>${c.hasCredential?'Credential saved':'No credential'}${c.allowPrivate?' · Private network allowed':''}</small>${button('Edit','edit-connection',c.id)}</article>`).join('')}</div>`+(!state.connections.length?empty('Connect your API','HTTP workflow steps use your own connection. The approval and export starter workflow needs no API.'): '');}
function activity(){const events=state.campaigns.flatMap(c=>c.events.map(e=>({...e,name:c.name}))).sort((a,b)=>b.at.localeCompare(a.at));return heading('Activity','Recorded execution events from your campaigns.')+`<div class="panel activity-list">${events.map(e=>`<div class="activity-row"><time>${esc(new Date(e.at).toLocaleString())}</time><div><strong>${esc(e.name)}</strong><p>${esc(e.text)}</p></div></div>`).join('')||'<p>No campaign events yet.</p>'}</div>`;}
function status(){return heading('System status','Your workspace and service configuration.')+`<div class="panel connection-card"><dl><div class="definition"><dt>Workspace</dt><dd>${esc(state.user.name)} · ${state.hosted?'Hosted':'Local'}</dd></div><div class="definition"><dt>Storage</dt><dd>Persistent SQLite workspace</dd></div><div class="definition"><dt>Execution</dt><dd>Server workflow runner. In-flight API writes require review after an interrupted result.</dd></div><div class="definition"><dt>Payments</dt><dd>${state.paymentsReady?'Configured; checkout also requires creator onboarding.':'Not configured. Free installs work.'}</dd></div></dl>${state.hosted?button('Sign out','logout'):''}</div>`;}
function assistant(){return heading('AI assistant','Ask for workflow planning help. Review and implement suggested steps in Creator studio.')+`<div class="panel ai-panel"><p>The assistant does not start campaigns or publish changes.</p><form id="assistant-form"><label>What would you like to automate?<textarea name="prompt" required rows="5"></textarea></label><button class="primary">Ask assistant</button></form><div id="assistant-answer"></div></div>`;}
function login(){state=null;$('#app').innerHTML=heading('Open your workspace','Sign in or create a marketplace account.')+`<form id="auth-form" class="panel connection-card form-grid">${field('Name (for a new account)','name')}${field('Email','email','','email','required')}${field('Password','password','','password','required minlength="12"')}<label>Action<select name="mode"><option value="login">Sign in</option><option value="register">Create account</option></select></label><button class="primary">Continue</button><p id="auth-error" role="alert"></p></form>`;}
function campaignForm(packageId=''){const packages=state.packages,pkg=packages.find(p=>p.id===packageId)||packages[0];if(!pkg){view='marketplace';location.hash=view;render();toast('Install a workflow first.');return;}
 const slots=[...new Set(pkg.workflow.steps.filter(s=>s.type==='http').map(s=>s.config.connection))];modal('wizard','Create campaign',`<form id="campaign-form" class="form-grid">${field('Campaign name','name','','text','required maxlength="100"')}<label>Installed workflow<select name="packageId">${packages.map(p=>`<option value="${esc(p.id)}" ${p.id===pkg.id?'selected':''}>${esc(p.workflow.title)} v${esc(p.workflow.version)}</option>`).join('')}</select></label>${slots.map(slot=>`<label>Connection for ${esc(slot)}<select name="binding:${esc(slot)}" required><option value="">Choose a saved connection</option>${state.connections.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label>`).join('')}${area('Records (CSV with headings or a JSON array)','records','name,email\nAlex,alex@example.invalid','required rows="7"')}<label class="full">Import a CSV or JSON file<input type="file" id="record-file" accept=".csv,.json,text/csv,application/json"></label><p class="full">${esc(pkg.workflow.description)}<br>Creating a campaign saves a draft. Use Start after reviewing its steps and records.</p><button class="primary">Create draft campaign</button><p class="form-error full" role="alert"></p></form>`);}
function showDetails(id,open=true){const c=state.campaigns.find(c=>c.id===id);if(!c)return;detailId=id;const actions=c.status==='draft'?['start','cancel']:c.status==='running'?['pause','cancel']:['paused','waiting'].includes(c.status)?['resume','cancel']:c.records.some(r=>r.status==='failed')?['retry']:[];
 const content=`<p>${esc(c.workflow.title)} v${esc(c.workflow.version)} · <strong>${esc(c.status)}</strong></p><div class="flow">${c.workflow.steps.map(s=>`<span>${esc(s.label)}</span>`).join(' → ')}</div><div class="detail-actions">${actions.map(a=>button(a[0].toUpperCase()+a.slice(1),'campaign-'+a,c.id,a==='start'?'primary':'')).join('')}<a href="/api/runtime/campaigns/export?id=${encodeURIComponent(c.id)}&format=csv" download>Export CSV</a><a href="/api/runtime/campaigns/export?id=${encodeURIComponent(c.id)}" target="_blank" rel="noopener">Export JSON</a></div><div class="table-scroll"><table class="details-table"><thead><tr><th>Record</th><th>Input</th><th>Status</th><th>Result / action</th></tr></thead><tbody>${c.records.map(r=>`<tr><td>${r.index+1}</td><td><pre>${esc(pretty(r.data))}</pre></td><td>${esc(r.status)}</td><td>${esc(r.message)}${r.status==='review'?`<div class="detail-actions">${button(r.uncertain?'Remote write succeeded':'Approve','review-approve',r.id)}${button('Reject','review-reject',r.id)}${r.uncertain?button('Retry remote write','review-retry',r.id):''}</div>`:''}<details><summary>Step results</summary><pre>${esc(pretty(r.outputs))}</pre></details></td></tr>`).join('')}</tbody></table></div><div class="event-log">${c.events.slice(-20).reverse().map(e=>`<div><time>${esc(new Date(e.at).toLocaleTimeString())}</time>${esc(e.text)}</div>`).join('')}</div>`;
 if(open)modal('details',c.name,content);else $('#details .modal-body').innerHTML=content;}
function connectionForm(id){const c=state.connections.find(c=>c.id===id)||{};modal('wizard',c.id?'Edit connection':'Add API connection',`<form id="connection-form" class="form-grid" data-id="${esc(c.id||'')}">${field('Connection name','name',c.name,'text','required')}${field('API origin','origin',c.origin||'https://api.example.com','url','required')}${field('Credential (blank keeps existing)','credential','','password','autocomplete="new-password"')}<label>Credential header<select name="header"><option value="authorization">Authorization: Bearer</option><option value="x-api-key">X-API-Key</option><option value="api-key">API-Key</option></select></label><label class="full"><input type="checkbox" name="allowPrivate" ${c.allowPrivate?'checked':''}> Allow an API on my private network (administrator only)</label><button class="primary">Save connection</button><p class="form-error full" role="alert"></p></form>`);}
function configFields(s,i){const prefix='s'+i+'_',c=s.config,f=(l,k,v,t='text')=>field(l,prefix+k,v,t),a=(l,k,v)=>area(l,prefix+k,v);let html='';
 if(s.type==='validate')html=f('Required fields (comma separated)','required',c.required.join(', '));
 if(s.type==='set')html=a('Field values (JSON; {{name}} inserts an input value)','values',pretty(c.values));
 if(s.type==='http')html=f('Connection slot','connection',c.connection)+`<label>HTTP method<select name="${prefix}method">${['GET','POST','PUT','PATCH','DELETE'].map(m=>`<option ${m===c.method?'selected':''}>${m}</option>`).join('')}</select></label>`+f('Relative API path','path',c.path)+f('Timeout (seconds)','timeoutSeconds',c.timeoutSeconds,'number')+a('JSON body (null for no body)','body',pretty(c.body));
 if(s.type==='review')html=a('Owner review message','message',c.message);
 if(s.type==='wait')html=f('Wait seconds','seconds',c.seconds,'number');
 if(s.type==='export')html=f('Export field names (comma separated)','fields',c.fields.join(', '));
 return html+f('Condition field (optional)','when_field',s.when?.field||'')+`<label>Run when<select name="${prefix}when_operator">${['equals','not_equals','exists'].map(o=>`<option ${o===s.when?.operator?'selected':''}>${o}</option>`).join('')}</select></label>`+f('Condition value','when_value',s.when?.value==null?'':String(s.when.value));}
function editor(draft){editing=draft||{workflow:newWorkflow()};drawEditor();}
function drawEditor(){const w=editing.workflow;modal('wizard','Workflow editor',`<form id="workflow-form" class="form-grid">${field('Workflow title','title',w.title,'text','required maxlength="100"')}${field('Version','version',w.version,'text','required')}${area('Description','description',w.description,'required minlength="20"')}${field('Price in USD cents (0 is free)','priceCents',w.priceCents,'number','min="0" max="999900" required')}${field('Category','category',w.category)}<div class="full"><h3>Executable steps</h3><p>Steps run in order. Templates can reference {{name}}, {{record.email}}, or {{steps.step1.data.id}}.</p>${w.steps.map((s,i)=>`<fieldset class="runtime-step"><legend>Step ${i+1}</legend><div class="form-grid">${field('Step identifier','s'+i+'_id',s.id)}${field('Step label','s'+i+'_label',s.label)}<label>Step type<select data-step-type="${i}" name="s${i}_type">${['validate','set','http','review','wait','export'].map(t=>`<option ${t===s.type?'selected':''}>${t}</option>`).join('')}</select></label><div class="detail-actions">${button('Move up','step-up',i)}${button('Remove','step-remove',i)}</div>${configFields(s,i)}</div></fieldset>`).join('')}${button('Add step','step-add')}</div><button class="primary">Save draft</button><p class="form-error full" role="alert"></p></form>`);}
function readEditor(){const f=new FormData($('#workflow-form')),w=editing.workflow,csv=k=>String(f.get(k)||'').split(',').map(x=>x.trim()).filter(Boolean);const steps=w.steps.map((s,i)=>{const p='s'+i+'_',v=k=>f.get(p+k);let config;
 if(s.type==='validate')config={required:csv(p+'required')};if(s.type==='set')config={values:JSON.parse(v('values'))};if(s.type==='http')config={connection:v('connection'),method:v('method'),path:v('path'),timeoutSeconds:Number(v('timeoutSeconds')),body:JSON.parse(v('body'))};if(s.type==='review')config={message:v('message')};if(s.type==='wait')config={seconds:Number(v('seconds'))};if(s.type==='export')config={fields:csv(p+'fields')};let value=v('when_value');try{value=JSON.parse(value);}catch{}return {id:v('id'),label:v('label'),type:s.type,config,when:v('when_field')?{field:v('when_field'),operator:v('when_operator'),value}:null};});editing.workflow={title:f.get('title'),description:f.get('description'),version:f.get('version'),priceCents:Number(f.get('priceCents')),category:f.get('category'),steps};}
async function act(action,id,target){
 if(action==='close'){target.closest('dialog').close();detailId=null;render();return;}
 if(action==='nav'){location.hash=id;return;}if(action==='new-campaign')return campaignForm(id);if(action==='details')return showDetails(id);if(action==='new-connection'||action==='edit-connection')return connectionForm(id);if(action==='new-workflow')return editor();if(action==='edit-workflow')return editor(structuredClone(state.drafts.find(d=>d.id===id)));
 if(action.startsWith('step-')){readEditor();const steps=editing.workflow.steps,i=Number(id);if(action==='step-add')steps.push({id:'step'+Date.now(),label:'Owner review',type:'review',config:defaultStep('review')});if(action==='step-remove')steps.splice(i,1);if(action==='step-up'&&i>0)[steps[i-1],steps[i]]=[steps[i],steps[i-1]];drawEditor();return;}
 if(action==='install'){const p=state.catalog.find(p=>p.id===id);const d=await request(p.workflow.priceCents?'marketplace/checkout':'marketplace/install',{packageId:id});if(d.result.url)window.open(d.result.url,'_blank','noopener');else toast('Workflow installed.');}
 if(action==='submit-workflow'){await request('workflows/submit',{id});toast('Submitted for publishing review.');}
 if(action==='publish'||action==='reject-publication'){await request('workflows/review',{id,decision:action==='publish'?'approve':'reject'});toast(action==='publish'?'Workflow published.':'Submission rejected.');}
 if(action.startsWith('campaign-'))await request('campaigns/action',{id,action:action.slice(9)});
 if(action.startsWith('review-'))await request('campaigns/review',{id:detailId,recordId:id,decision:action.slice(7)});
 if(action==='onboard'){const d=await request('marketplace/onboard',{});window.open(d.result.url,'_blank','noopener');}
 if(action==='logout'){await request('auth/logout',{});login();return;}
 await refresh();if(!$('dialog[open]'))render();}
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-nav]');if(nav){location.hash=nav.dataset.nav;return;}const b=e.target.closest('[data-action]');if(!b)return;e.preventDefault();b.disabled=true;try{await act(b.dataset.action,b.dataset.id,b);}catch(err){toast(err.message);}finally{b.disabled=false;}});
document.addEventListener('change',async e=>{try{if(e.target.name==='packageId'){const form=$('#campaign-form'),name=form.elements.name.value,records=form.elements.records.value;campaignForm(e.target.value);$('#campaign-form').elements.name.value=name;$('#campaign-form').elements.records.value=records;}
 if(e.target.id==='record-file'){const file=e.target.files[0];if(file){if(file.size>1000000)throw Error('Import a file up to 1 MB.');$('#campaign-form').elements.records.value=await file.text();}}
 if(e.target.dataset.stepType!==undefined){const i=Number(e.target.dataset.stepType),type=e.target.value;readEditor();editing.workflow.steps[i].type=type;editing.workflow.steps[i].config=defaultStep(type);drawEditor();}}catch(err){toast(err.message);}});
document.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,f=new FormData(form),submit=form.querySelector('button[type="submit"],button.primary');if(submit)submit.disabled=true;try{
 if(form.id==='auth-form'){await request('auth/'+f.get('mode'),Object.fromEntries(f));form.remove();await refresh();render();return;}
 if(form.id==='campaign-form'){const bindings=Object.fromEntries([...f].filter(([k])=>k.startsWith('binding:')).map(([k,v])=>[k.slice(8),v]));await request('campaigns/create',{name:f.get('name'),packageId:f.get('packageId'),records:parseRecords(f.get('records')),bindings});}
 if(form.id==='connection-form'){const input={id:form.dataset.id||undefined,name:f.get('name'),origin:f.get('origin'),allowPrivate:f.has('allowPrivate')};if(f.get('credential')){input.credential=f.get('credential');input.header=f.get('header');}await request('connections/save',input);}
 if(form.id==='workflow-form'){readEditor();await request('workflows/save',{id:editing.id,revision:editing.revision,workflow:editing.workflow});}
 if(form.id==='assistant-form'){const {csrf}=await fetch('/api/session').then(r=>r.json());const r=await fetch('/api/ai/chat',{method:'POST',headers:{'content-type':'application/json','x-hyperaccts-token':csrf},body:JSON.stringify({messages:[{role:'user',content:f.get('prompt')}]})});const d=await r.json();if(!r.ok)throw Error(d.message||'Assistant unavailable.');$('#assistant-answer').textContent=d.message||d.reply||d.text||pretty(d);return;}
 form.closest('dialog')?.close();await refresh();render();toast('Saved.');
 }catch(err){const error=form.querySelector('.form-error,#auth-error');if(error)error.textContent=err.message;else toast(err.message);}finally{if(submit)submit.disabled=false;}});
window.addEventListener('hashchange',()=>{view=location.hash.slice(1)||'campaigns';render();});$('#details').addEventListener('close',()=>{detailId=null;});refresh();setInterval(refresh,2000);
